# Statistics Software

## SAS

The UNL Statistics department offers SAS installations through Steve Westerholt for $65. Please contact Alison Reckewey at areckewey2@unl.edu or visit the main statistics office at Hardin 340.

## R

1. Download and run the R installer for your operating system from CRAN:

+ Windows: https://cran.rstudio.com/bin/windows/base/
+ Mac: https://cran.rstudio.com/bin/macosx/
+ Linux: https://cran.rstudio.com/bin/linux/ (pick your distribution)

If you are on Windows, you should also install the [Rtools4 package](https://cran.rstudio.com/bin/windows/Rtools/); this will ensure you get fewer warnings later when installing packages.

More detailed instructions for Windows are available [here](https://owi.usgs.gov/R/training-curriculum/installr/index.html)

2. Download and install the [latest version of RStudio](https://www.rstudio.com/products/rstudio/download/#download) for your operating system. RStudio is a integrated development environment (IDE) for R - it contains a set of tools designed to make writing R code easier.

## Other

While there are a handful of other statistical software tools, our consultants are most well versed in R and SAS. Below are a few others that you may be familiar with. Our consultants may be able to provide basic interpretation of results from these.

+ SPSS
+ MPlus